### ISSUE TITLE
alba build in docker for arch & ubuntu 16.04 + documentation

### ISSUE THREAD

**Issue by despiegk** [openvstorage/alba#188]
- docker build for arch & ubuntu 16.04
- explain how to build by means of docker (documentation)

**Comment by domsj** [comment]
On the 'ubuntu-16.04' branch there are docker images for ubuntu 16.04 and for arch linux, see https://github.com/openvstorage/alba/tree/ubuntu-16.04/docker .
https://github.com/openvstorage/alba/blob/ubuntu-16.04/COMPILING.md has been updated to show how to build alba using an ubuntu 16.04 docker image.
The arch linux docker file shows the steps needed to get arakoon built. Building alba is a few more steps, but need to focus on some feature development now.

**Comment by despiegk** [comment]
@domsj are there code changes required? if so how much

**Comment by domsj** [comment]
no, no code changes are required

**Comment by wimpers** [comment]
As discussed last Friday with @despiegk  Arch Linux isn't required.

**Comment by domsj** [comment]
this was fixed in #313
