### ISSUE TITLE
Use fadvice after upload of SCO

### ISSUE THREAD

**Issue by wimpers** [openvstorage/alba#202]
Leaving uploaded SCO in the page cache makes no sense. Let the proxy use fadvice to give the kernel a hint for the SCO to be evicted from the page cache.

**Comment by domsj** [comment]
Looks like we already do this. It's even configurable in the proxy config file using the 'use_fadvise' property, see https://github.com/openvstorage/alba/blob/master/cfg/proxy_demo.json#L24-L25 .
It defaults to true (which is what you want), so no integration needed from the framework side.
