### ISSUE TITLE
Make sure that the quorum flag is passed using etcdctl

### ISSUE THREAD

**Issue by khenderick** [openvstorage/alba#207]
Make sure that the quorum flag is passed using etcdctl

**Comment by domsj** [comment]
This will be fixed in alba once we update it to a newer arakoon. If I don't forget I will then close this issue.

**Comment by wimpers** [comment]
@domsj any update on the new Arakoon?

**Comment by domsj** [comment]
No new arakoon yet. Is it urgent?

The alba/arakoon planning I had in mind was something like this:
- finish alba-as-asd branch (global vs local backend etc)
- fix http://jira.openvstorage.com/browse/OVS-3938 (arakoon should take a lock on e.g. a file in it's home dir). http://jira.openvstorage.com/browse/OVS-4539 is also related to this
- release a new arakoon
- update alba to latest arakoon
- fix #211 & #197 by updating to a newer version of rocksdb
- maybe have a look at #209 to see if it's a quick fix or not
- wait for gobjfs work from @toolslive (if not yet finished by then)
- release a new alba

What do you think @wimpers? I can make new releases sooner too if you want that...

**Comment by domsj** [comment]
Forgot to mention: before making a new alba I would like to fix #213 too

**Comment by wimpers** [comment]
@domsj no problem. It isn't urgent as long as this one is fixed before we release.

**Comment by domsj** [comment]
updated to latest arakoon in #222
