### ISSUE TITLE
Negative usage on asds

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/alba#209]
```
alba version
0.9.5
git_revision: "tags/0.9.5-0-ge4cf366"
git_repo: "https://github.com/openvstorage/alba.git"
compile_time: "11/05/2016 15:40:26 UTC"
machine: "455badec0dde 3.13.0-24-generic x86_64 x86_64 x86_64 GNU/Linux"
compiler_version: "4.02.3"
```

On regular time intervals, asds/backend usage shows negative values. (see screenshots)
After restarting the asd the negative value disappears and the correct value is shown.

Negative used_bytes:

```
root@str02:~# alba list-osds --config etcd://127.0.0.1:2379/ovs/arakoon/be-backend-abm/config | grep oyR
2016/05/26 15:20:10 286478 +0200 - str02 - 1403/0 - alba/cli - 0 - info - ETCD: etcdctl --peers=127.0.0.1:2379 get ovs/arakoon/be-backend-abm/config                             "oyRgZLZKDUVXts1birJ1IceDxUJ32EsH");
  other = "{ \"id\" : \"oyRgZLZKDUVXts1birJ1IceDxUJ32EsH\", \"node_id\" : \"qNqsb2zoMLDE7iCAkSBpNz24a27iwDNX\", \"port\" : 8603, \"used_bytes\" : \"-187152090328\", \"total_bytes\" : \"1999018582016\", \"version\" : \"AsdV1\", \"network_interfaces\":[ ]}";
```

Restarting asd (correct value):

```
root@str02:~# restart alba-asd-oyRgZLZKDUVXts1birJ1IceDxUJ32EsH
alba-asd-oyRgZLZKDUVXts1birJ1IceDxUJ32EsH start/running, process 10051

root@str02:~# alba list-osds --config etcd://127.0.0.1:2379/ovs/arakoon/be-backend-abm/config | grep oyR
2016/05/26 15:23:05 632690 +0200 - str02 - 11000/0 - alba/cli - 0 - info - ETCD: etcdctl --peers=127.0.0.1:2379 get ovs/arakoon/be-backend-abm/config                             "oyRgZLZKDUVXts1birJ1IceDxUJ32EsH");
  other = "{ \"id\" : \"oyRgZLZKDUVXts1birJ1IceDxUJ32EsH\", \"node_id\" : \"qNqsb2zoMLDE7iCAkSBpNz24a27iwDNX\", \"port\" : 8603, \"used_bytes\" : \"874780016\", \"total_bytes\" : \"1999018582016\", \"version\" : \"AsdV1\", \"network_interfaces\":[ ]}";
```

![backend_size](https://cloud.githubusercontent.com/assets/2900612/15576398/f2e89a2c-2357-11e6-95e7-d359c2cf84ea.png)
![negative_asd](https://cloud.githubusercontent.com/assets/2900612/15576397/f2e32308-2357-11e6-9a40-0183b1eda3be.png)
[alba-asd-oyRgZLZKDUVXts1birJ1IceDxUJ32EsH.txt](https://github.com/openvstorage/alba/files/284467/alba-asd-oyRgZLZKDUVXts1birJ1IceDxUJ32EsH.txt)

**Comment by wimpers** [comment]
@jeroenmaelbrancke I had a small chat about this ticket with @domsj and we believe this was fixed. Did you see this negative asd value behavior the last few weeks/months? Can we close it as fixed and re-open if needed?

**Comment by jeroenmaelbrancke** [comment]
You can close this ticket now.
We did not see negative asd values the last few weeks.

**Comment by wimpers** [comment]
After discussion with OPS and ENG set to closed. Re-open if needed.

**Comment by domsj** [comment]
Saw this again on @dejonghb's env

**Comment by toolslive** [comment]
In that case, the ASD dies with exit code 666. @jeroenmaelbrancke  Does monitoring pick this up?
Have we seen this recently?

**Comment by jeroenmaelbrancke** [comment]
We did not implement the usage from the asds with the alba API because Check mk automatically monitor the usage of the mountpoints.

![mountpoints](https://cloud.githubusercontent.com/assets/2900612/22468040/439ea41e-e7c7-11e6-8a66-81204a2143eb.png)

**Comment by wimpers** [comment]
@jeroenmaelbrancke  can you enable the log monitoring to monitor this exit code 666 so we have an idea how many times it occurs

**Comment by jeroenmaelbrancke** [comment]
@toolslive will log some information when the process exit.
Ping me when you have an example log so i can create the alert rule in ElastAlert.

**Comment by toolslive** [comment]
it will log a string `negative disk usage detected` on `fatal` level just before the end.
