### ISSUE TITLE
asds are consuming a lot of memory

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba#210]
Saw this on an environment for some ASD processes:
```
25684 alba      20   0 4205312 1.355g   2844 S   7.0 17.4  19:32.72 alba                                                                                                                    
25665 alba      20   0 3815164 1.318g   3272 S   6.6 16.9  19:04.92 alba                                                                                                                    
25735 alba      20   0 3436292 1.261g   4324 S   6.6 16.2  19:35.33 alba                                                                                                                    
25698 alba      20   0 4037040 1.373g   3436 S   6.3 17.6  19:26.40 alba                                                                                                                    
25717 alba      20   0 3318696 1.244g   3716 S   4.3 16.0  19:00.52 alba
```

Apparently there is somebody working on determing the amount of memory for the ASDs: https://github.com/ovs-projects/org_development/issues/25

Currently the config says that the amount of memory that can be used is 0.25% equivalent to its own disk space. Maybe this is to ambitious? For 1.5TB disk this is in theory 3.75GB of memory.

**Comment by wimpers** [comment]
@eduardBM please close once verified

**Comment by eduardBM** [comment]
@wimpers, i don't see this situation on my environment, so i guess this can be closed.
@kinvaris, can you give more details about the setup (version, nr. of nodes, nr. of volumes, nr. of vms running).

Related to https://github.com/ovs-projects/org_development/issues/25 i set the rocksdb blockCache to 0.00025% (so 250MiB for 1TiB disk). Not sure how this translates to amount of memory used.

**Comment by wimpers** [comment]
@kinvaris , re-open if needed.

**Comment by kinvaris** [comment]
@eduardBM: What you changed to the rocksdb blockCache is related to the memory...
