### ISSUE TITLE
Asds should also reload block cache size when sent a signal to reload (part of their) config

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#216]
Currently this mechanism is used by the framework to notify the capacity to be used by the asd. At the same time they will also reconfigure the block cache size, so we should probably take that change into account then too.
Not sure if rocksdb allows us to change this for an already opened database... otherwise we may have to close and reopen it with the changed settings.

**Comment by domsj** [comment]
I've already made a necessary change to rocksdb: https://github.com/facebook/rocksdb/pull/1149

**Comment by wimpers** [comment]
Moved to Gilbert as non SRP.
