### ISSUE TITLE
Command alba cache-eviction should be able to get params out of configuration file

### ISSUE THREAD

**Issue by khenderick** [openvstorage/alba#221]
Command ```alba cache-eviction``` should be able to get params out of configuration file.

At this point, a ```--prefix``` and ```--preset``` must be passed along, but we most likely want to use eviction processes for multiple prefixes and presets.

**Comment by domsj** [comment]
As an alternative for this issue we also discussed another scenario:
- no separate cache eviction process
- run cache eviction inside the maintenance processes of the backend that is used as a cache
- when a backend starts using another backend as a cache this should be notified towards the cache backend (so it can persist this info, and the maintenance processes can take it into account)

**Comment by wimpers** [comment]
To be tackled in https://github.com/ovs-projects/org_development/issues/18
