### ISSUE TITLE
Noticed several Arakoon_etcd.ProcessFailure(_) when issuing list-presets / add-preset cli commands

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/alba#235]
Cause: due to Etcd timeout, the alba-cli command returns Arakoon_etcd.ProcessFailure()

Noticed in backend suite on:
- single node env:  http://testrail.openvstorage.com/index.php?/plans/view/32791
- grid env:  http://testrail.openvstorage.com/index.php?/runs/view/32786

**Comment by wimpers** [comment]
@pploegaert what would be a sane timeout setting?

**Comment by domsj** [comment]
This isn't really an alba issue ... alba can't help that central config management is temporary unavailable. So can this issue be closed?
(Side note: the switch from etcd to arakoon doesn't solve the fundamental issue ... central config management might still be down. Fwiw for these kind of calls a slightly outdated config file could in many cases work just as well.)

**Comment by wimpers** [comment]
Back to BAM
