### ISSUE TITLE
need better doc

### ISSUE THREAD

**Issue by despiegk** [openvstorage/alba#245]
e.g. https://github.com/openvstorage/alba/blob/master/doc/dependencies.md scrambled text

there are .tex docu in there, I though we wanted .md

is the doc about docker still ok

please lets cleanup

**Comment by despiegk** [comment]
fyi there are nice plugins on gitbook like mermaid
they can be used for the graphs no need to use latex

please lets use same format everywhere, just md

also many docs seem to be old

**Comment by toolslive** [comment]
- the dependencies document was what we kept in our repo to be able to generate the confluence dependency page that needed to be kept up to date. (fwiw, it looks great on confluence)
- you might want markdown, but I haven't been able to find anything that can render a simple math formula on github. I quickly took a look at mermaid, and it's (too) limited. 

So we used latex, generated a pdf and put it in the repo.

**Comment by wimpers** [comment]
* https://openvstorage.gitbooks.io/alba/content/docs/dependencies.html
