### ISSUE TITLE
need better doc how to install only using alba components

### ISSUE THREAD

**Issue by despiegk** [openvstorage/alba#246]
- starting from the docker builds
- then guidelines about config files (can't find)
- how to start
- what is what

people need to be able to deploy this project without having to know anything else apart from arakoon

**Comment by wimpers** [comment]
* What is what is described under https://openvstorage.gitbooks.io/alba/content/docs/
* How to build https://github.com/openvstorage/alba/blob/master/COMPILING.md
* Setup guide https://openvstorage.gitbooks.io/alba/content/docs/setup-guide.html
* Config files are documented under https://openvstorage.gitbooks.io/framework-alba-plugin/content/docs/etcd.html as this is where these config files are set up.

Re-open if additional documentation is required.
