### ISSUE TITLE
statistics (doc)

### ISSUE THREAD

**Issue by despiegk** [openvstorage/alba#248]
we would like to understand how to get statistics from alba
we want to store in influxdb
what is best approach to get stats out of alba?

**Comment by despiegk** [comment]
is there documentation?

**Comment by wimpers** [comment]
@jeroenmaelbrancke can you provide info or point to the script/documentation you are creating/created.

**Comment by jeroenmaelbrancke** [comment]
@wimpers I'm finishing the ansible installation scripts with redis integration.
Documentation is still in process on confluence and will convert this to gitbook when this is approved by someone from my team.
+ The ansible scripts will be available on the openvstorage monitoring repo when the documentation is finished.

**Comment by wimpers** [comment]
@despiegk https://openvstorage.gitbooks.io/ovs-monitoring/content/

**Comment by JeffreyDevloo** [comment]
The gitbook contains the standard procedure that we use ourselves for monitoring statistics.
