### ISSUE TITLE
Document alba C client

### ISSUE THREAD

**Issue by wimpers** [openvstorage/alba#249]
Document the alba C++ client.

**Comment by wimpers** [comment]
@toolslive @domsj anywhere I can find some internal documentation around this?

**Comment by domsj** [comment]
We have a C++ client, not a C client.
There is no documentation, but usage of the client is rather straightforward.
See https://github.com/openvstorage/alba/blob/master/cpp/src/examples/test_client.cc for a simple program that uses it.
sample usage: https://github.com/openvstorage/alba/blob/master/cpp/src/examples/test_client.cc#L161-L162
proxy client interface: https://github.com/openvstorage/alba/blob/master/cpp/include/proxy_client.h

**Comment by wimpers** [comment]
https://openvstorage.gitbooks.io/alba/content/docs/client.html

**Comment by wimpers** [comment]
https://openvstorage.gitbooks.io/alba/content/docs/client.html

**Comment by wimpers** [comment]
@despiegk let me know if more info would be required
