### ISSUE TITLE
Put timeouts on CLi commands

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba#264]
We noticed on some environments that the Alba CLi commands were stuck because of `max connections reached` on a ABM. This was caused by the fact that multiple commands were called but it had no timout (and this lead to `max connections reached`).

Maybe it would be interesting to put a timeout on every Cli command to avoid such encounters.

**Comment by kinvaris** [comment]
https://github.com/openvstorage/framework/issues/675

**Comment by toolslive** [comment]
If you ever see an alba cli command that hangs, open a ticket that contains the actual cli command.
