### ISSUE TITLE
asd-discovery detects asds from another env and tries to connect while it shouldn't

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/alba#269]
asd-discovery process detects asds belonging to another alba and tries to connect but it doesn't have the hardware required to do that
To be investigated

```
alba asd-discovery
....
        total = 102621958144L; used = 7737179L }) ; ips = ["172.23.154.231"]; port = (Some 8003) ; tlsPort = None ; useRdma = true ; }
{extras: (Some { Discovery.node_id = "1b2e6925_0"; version = "AsdV1";
        total = 102621958144L; used = 10915628L }) ; ips = ["172.23.154.231"]; port = (Some 8001) ; tlsPort = None ; useRdma = true ; }
....
```

```
2016-06-29 09:37:57 138539 +0200 - allflash184 - 28768/0 - alba/proxy - 1016994 - debug - Error during check osd claimed thread (for 8000_00_1b2e6925): (Unix.Unix_error "No such device" socket ""); backtrace:; Raised at file "format.ml", line 185, characters 41-52; Called from file "format.ml", line 427, characters 6-24
```

**Comment by domsj** [comment]
This behaviour was in the past considered as a feature ...
Disabling it (either by default or entirely) would be a backwards compatibility breaking change for alba.
But it can be done if first some changes are made to the framework.

**Comment by wimpers** [comment]
Please lay your egg what should be done.

**Comment by saelbrec** [comment]
From the FWK point of view this isn't used anymore for Alba ASD's, but what in case of Kinetic, @toolslive ? This will have to be re-introduced?

**Comment by toolslive** [comment]
For Kinetic, this isn't an issue as you'll always have the hardware to connect to the drive you've discovered: It's always ethernet. 
A possible solution is that a component (proxy/maintenance) could be given the extra information that it has rdma capable hardware at startup time (configuration/flag) and use that information before trying to connect to rdma based ASDs.

**Comment by domsj** [comment]
If I understand correctly no further solution is needed (for how deployments are currently done by the framework).
Asds and Kinetics are both only configured to NOT use rdma, so all proxies/maintenance should be able to connect to any asd/kinetic.

**Comment by toolslive** [comment]
Indeed.
