### ISSUE TITLE
Removing many vdisks at once causes issues on the backend

### ISSUE THREAD

**Issue by wimpers** [openvstorage/alba#278]
In case you remove many vdisks at the same time, the backend will have issues and the ASDs will go in red. This has as result that you end up with unsatisfiable policy errors in some cases.

**Comment by domsj** [comment]
The maintenance process causes too much load when cleaning up blobs for the deleted namespace.
There is some throttling already present in the asds to limit how much impact maintenance (repair etc) can have, but apparently it is (wasn't) there yet for fragment cleanup.

**Comment by domsj** [comment]
Please try again when alba 0.9.14 has been released
