### ISSUE TITLE
Lazy write out

### ISSUE THREAD

**Issue by wimpers** [openvstorage/alba#302]
We should optimize the write process by allowing a lazy write out where we acknowledge a write in case c fragments have been stored correctly. Currently we only do this in case of a disaster scenario but we should do this by default.

**Comment by toolslive** [comment]
The primary use case in mind is a slow link to one of the data centers.

**Comment by domsj** [comment]
Yes, and the secondary use cases would be 
- slow (deteriorating) disk (but just not slow enough)
- first failure of some osd

All can be nicely handled with the strategy discussed on the chat.

Actually this already helps for https://github.com/openvstorage/alba/issues/418 too (node goes down, takes some time to disqualify all osds) in case the disqualified node would still result in the same policy being chosen.

**Comment by wimpers** [comment]
Maybe you can share that strategy with the rest of the world also?

**Comment by toolslive** [comment]
Basically it's this:
- wait until `min_fragment_count fragments` have been written (this takes `t`)
- wait for a small arbitrary period (fe `0.2t`) for the slowpokes to arrive
- build the manifest with what you have at that point for the manifest and continue 
- if there are still outstanding writes that come in later, use those and update the manifest.

**Comment by domsj** [comment]
We could also make the 0.2t configurable if desired.
Then you could e.g. have 0t in which case the upload has the lowest possible latency, or it could be 10000t in which case it would (probably) wait until the osd_timeout happens, or it could be some value chosen based on some testing for the specific environment.
(Making a good default choice for an arbitrary timeout is always hard...)
