### ISSUE TITLE
RDMA Proxy client's timeout shouldn't be based on gettimeofday

### ISSUE THREAD

**Issue by redlicha** [openvstorage/alba#318]
Discovered via code inspection while debugging https://github.com/openvstorage/alba/issues/317 :
```
double _stamp_ms() {
  struct timeval tp;
  gettimeofday(&tp, NULL);
  double t0 = 1000 * tp.tv_sec + (double)tp.tv_usec / 1e3;
  return t0;
}
```

`gettimeofday` returns the wall clock time - better use a steady clock, e.g. `boost::chrono::steady_clock` - http://www.boost.org/doc/libs/1_61_0/doc/html/chrono/reference.html#chrono.reference.cpp0x.system_clocks_hpp.steady_clock , e.g. (pseudo code!):

```
auto end = boost::chrono::steady_clock::now() + timeout_duration;
do
{
    // ... work
}
while (boost::chrono::steady_clock::now() < end)
```

**Comment by domsj** [comment]
fixed in #325
