### ISSUE TITLE
Rora fetcher manifest cache eviction will constantly evict the same items

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#330]
https://github.com/openvstorage/alba/pull/299#discussion_r72932737
And if those items are hot then performance might suffer...

**Comment by toolslive** [comment]
currently it's [random and expensive](https://github.com/openvstorage/alba/blob/master/cpp/src/lib/manifest_cache.cc#L73-L74).

**Comment by toolslive** [comment]
addressed in #342
