### ISSUE TITLE
Expose conditional write call in C++ API

### ISSUE THREAD

**Issue by redlicha** [openvstorage/alba#353]
Specific use case: upload an object O only if an object C's SHA-1 matches the expectations (while permitting to specify O's checksum and whether overwrites are accepted or not).

**Comment by domsj** [comment]
simplifies https://github.com/openvstorage/alba/issues/217

**Comment by wimpers** [comment]
@domsj isn't this completed yet? I believe Kenneth is looking to integrate the fencing?

**Comment by domsj** [comment]
this has indeed been merged, closing
