### ISSUE TITLE
RORA: support for small fragments

### ISSUE THREAD

**Issue by toolslive** [openvstorage/alba#360]
When the fragment is small, it's put in rocksdb. A rora partial read for something inside that fragment will fail, and the fragment will be fetched via the long route (aka proxy). 
This causes poor performance, and happens more often than previously anticipated.

**Comment by wimpers** [comment]
Removed SRP label as it is a corner case and not causing general performance issues.

**Comment by toolslive** [comment]
This issue is left in a void state. Sure, gobjfs still has no support for this (honestly, 
I don't think it ever will), 
but the alternative short path that's in use since Alba 1.3.3 does.
