### ISSUE TITLE
Default replication policy is dangerous

### ISSUE THREAD

**Issue by wimpers** [openvstorage/alba#361]
If you select 3-way replication the policy is (1, 2, 1, 3). If you use this policy across a global backend (3 datacenters), there is no guarantee a copy will be available in each datacenter. A better approach would be to use (1,2,1,**1**).

**Comment by domsj** [comment]
Don't you want to suggest (1,2,2,x) instead?

I think each local backend is considered to be part of it's own 'node', so the last constraint actually doesn't do much in this case.
And if they are not part of different nodes, then your suggestion would result in storing maximum 1 copy...

Btw: you want to move this ticket to the https://github.com/openvstorage/framework-alba-plugin repo.
