### ISSUE TITLE
File descriptor leak in proxy & maintenance when redis lru eviction has been configured but redis is not available

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#379]
This is due to a bug in ocaml-redis.
It has been fixed in https://github.com/0xffea/ocaml-redis/pull/35.
Code inspection also revealed another fd leak issue, fixed in https://github.com/0xffea/ocaml-redis/pull/37.
Both are as of yet unavailable in a released version. Not sure if we should wait for a new release, or just use latest version from master.

@aluuu any ETA on a new ocaml-redis release?

**Comment by aluuu** [comment]
Hi,

Thanks for PR you've made. I'll ship new version as soon as possible due to these two major fixes.

**Comment by domsj** [comment]
Ok, thanks @aluuu, looking forward to it.

**Comment by aluuu** [comment]
New version is [almost in OPAM](https://github.com/ocaml/opam-repository/pull/7486).

**Comment by domsj** [comment]
fixed by #383
