### ISSUE TITLE
Alba proxy & maintenance process should automatically pick up changed redis-lru config

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#381]
The current solution for lru eviction from the alba fragment cache allows specifying a redis instance to be used.
Only 1 ip can be specified. If the host goes down, they may want to configure another redis instance on another host to be used for the lru tracking.
This is possible, but afterwards they'll have to restart all related proxy & maintenance processes.
This ticket is about eliminating the need for this restart.

**Comment by wimpers** [comment]
Redis-LRU is no longer supported and is replaced by random removal.
