### ISSUE TITLE
Client_helper.MasterLookupResult.Error(0) crashed albaproxy

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba#384]
Related to: http://tickets.openvstorage.com/browse/OVSSUP-123

Incident on GIG environment during their testing, this error was occuring on a single albaproxy and apparently it crashed: (to bad I don't have any syslogs...)

```
2016-09-25 15:57:03 828006 +0200 - stor-06.be-g8-4 - 15102/0 - alba/proxy - 7410 - info - reading from fd: 21824B in 2 steps
2016-09-25 15:57:03 828585 +0200 - stor-06.be-g8-4 - 15102/0 - alba/proxy - 7411 - info - reading from fd: 32768B in 2 steps
2016-09-25 15:57:03 831901 +0200 - stor-06.be-g8-4 - 15102/0 - alba/proxy - 7412 - info - reading from fd: 32768B in 2 steps
2016-09-25 15:57:03 832418 +0200 - stor-06.be-g8-4 - 15102/0 - alba/proxy - 7413 - info - reading from fd: 32768B in 2 steps
2016-09-25 15:57:03 872116 +0200 - stor-06.be-g8-4 - 15102/0 - alba/proxy - 7414 - info - reading from fd: 28672B in 2 steps
2016-09-25 15:57:03 872337 +0200 - stor-06.be-g8-4 - 15102/0 - alba/proxy - 7415 - info - reading from fd: 28672B in 2 steps
alba: internal error, uncaught exception:
      (Unix.Unix_error "Invalid argument" select "")
      Raised by primitive operation at file "lwt_rsocket.ml", line 452, characters 12-50
      Called from file "src/unix/lwt_main.ml", line 41, characters 8-82
      Called from file "src/cmdliner.ml", line 1350, characters 17-26
      Called from file "src/cmdliner.ml", line 1390, characters 6-34
alba: internal error, uncaught exception:
      Client_helper.MasterLookupResult.Error(0)
      Raised at file "src/core/lwt.ml", line 789, characters 22-23
      Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
      Called from file "src/cmdliner.ml", line 1350, characters 17-26
      Called from file "src/cmdliner.ml", line 1390, characters 6-34
alba: internal error, uncaught exception:
      Client_helper.MasterLookupResult.Error(0)
      Raised at file "src/core/lwt.ml", line 789, characters 22-23
      Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
      Called from file "src/cmdliner.ml", line 1350, characters 17-26
      Called from file "src/cmdliner.ml", line 1390, characters 6-34
alba: internal error, uncaught exception:
      Client_helper.MasterLookupResult.Error(0)
      Raised at file "src/core/lwt.ml", line 789, characters 22-23
      Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
      Called from file "src/cmdliner.ml", line 1350, characters 17-26
      Called from file "src/cmdliner.ml", line 1390, characters 6-34
alba: internal error, uncaught exception:
      Client_helper.MasterLookupResult.Error(0)
      Raised at file "src/core/lwt.ml", line 789, characters 22-23
      Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
      Called from file "src/cmdliner.ml", line 1350, characters 17-26
      Called from file "src/cmdliner.ml", line 1390, characters 6-34
```

**Comment by kinvaris** [comment]
Other proxies did not got this problem at that time...

**Comment by domsj** [comment]
What you see here is the following:
- proxy dies due to bug #314 
- next upstart tries to restart the proxy (up to 10 times), but that fails because central config management is down. see my earlier remark about that: https://github.com/openvstorage/alba/issues/235#issuecomment-246931468 .

In this case the proxy could be started just fine with a (possibly slightly) outdated config file.

What is a component supposed to do when central config management is unavailable?
Die (which is what we do now) or keep on retrying until it can finally get its config?

**Comment by domsj** [comment]
Fwiw the maintenance agent running on stor-03 had the exact same problem

**Comment by wimpers** [comment]
@domsj ,

It seems that it took between 1 to 2  minutes to elect a new master (based upon the logs).

`2016-09-25 15:54:48 802920 +0200 - stor-06.be-g8-4 - 20085/0 - arakoon - 2050056 - info - zdQD60YpyUdOkcyl is master
2016-09-25 15:55:48 883253 +0200 - stor-06.be-g8-4 - 20085/0 - arakoon - 2050494 - info - zdQD60YpyUdOkcyl is master
2016-09-25 15:57:18 736238 +0200 - stor-06.be-g8-4 - 20085/0 - arakoon - 2052487 - info - qdo7HrjbTiucOKKM is master
2016-09-25 15:58:18 975455 +0200 - stor-06.be-g8-4 - 20085/0 - arakoon - 2052993 - info - qdo7HrjbTiucOKKM is master
2016-09-25 15:59:19 458403 +0200 - stor-06.be-g8-4 - 20085/0 - arakoon - 2053512 - info - qdo7HrjbTiucOKKM is master`
 
Is that normal behaviour? 
* Yes: in that case we need to up the amount of retries or delay the upstart respawns.
* No: to be investigated why the master election took so long.

**Comment by domsj** [comment]
No, I don't consider it normal for master election to take that long.
If you can point towards the env (or just full logs) I can have a look.
So then we would consider it an arakoon issue.
But we should also still consider what has to happen when the cluster temporarily has no master. I wouldn't consider 20 seconds master switch to be abnormal, and that won't be handled nicely either.
So my (so far skilfully ignored) questions remain.

**Comment by wimpers** [comment]
@domsj check with @saelbrec  for the arakoon logs (stor-06.be-g8-4). 

> What is a component supposed to do when central config management is unavailable?
Retry a certain amount of times and if it can't connect, die.

>  I wouldn't consider 20 seconds master switch to be abnormal, and that won't be handled nicely either.
I don't understand why you say this. If a master selection takes 20s, the proxy can't start for 20 and will start once the master is selected. Why do you state it won't be handled nicely? What I'm missing here?

**Comment by matthiasdeblock** [comment]
Had the same issue with the maintenance agent as well on a GIG env.

```
2016-11-29 12:16:35 676839 +0100 - stor-01.cl-g8-uk1 - 5605/0 - alba/maintenance - 746 - warning - Exception in discovery loop. retrying in  0: Lwt.Canceled; backtrace:; Raised at file "map.ml", line 122, characters 16-25; Called from file "src/core/lwt.ml", line 161, ch
aracters 4-40
alba: main: found env var ALBA_LWT_ENGINE=libev
alba: main: found env var ALBA_LWT_ENGINE=libev
alba: internal error, uncaught exception:
      Client_helper.MasterLookupResult.Error(0)
      Raised at file "src/core/lwt.ml", line 789, characters 22-23
      Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
      Called from file "src/cmdliner.ml", line 1350, characters 17-26
      Called from file "src/cmdliner.ml", line 1390, characters 6-34
```

**Comment by wimpers** [comment]
Back to BAM

**Comment by pploegaert** [comment]
Related to: http://tickets.openvstorage.com/browse/OVSSUP-124

**Comment by toolslive** [comment]
> What is a component supposed to do when central config management is unavailable?
In this case, the component refuses to start. Which is perfectly acceptable.
