### ISSUE TITLE
Extend json output from show namespace

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/alba#394]
Alba version: 0.9.20

I'm unable to find the preset_name in the json output from the show-namespace command.
Without parsing the output to json you can find the preset_name = "globalpreset".

Without parsing to json:
```
alba show-namespace --config arakoon://config/ovs/vpools/8455b0ac-6466-40b3-ad82-985cffb2f226/proxies/169d1aba-0807-4d01-8169-362cd4cbbb94/config/abm?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini b851b8fd-2337-4c25-845c-cff0fb927f8e
(b851b8fd-2337-4c25-845c-cff0fb927f8e,{ Albamgr_protocol.Protocol.Namespace.id = 10l; nsm_host_id = "global_nsm_1";
  state = Albamgr_protocol.Protocol.Namespace.Active;
  preset_name = "globalpreset" })
logical: 33099000952
storage: 49648512096
storage_per_osd: [(0l, 16549504032L); (1l, 16549504032L); (2l, 16549504032L)]
bucket_count: [((2, 1, 3, 1), 8427L)]
```

json output:
```
alba show-namespace --config arakoon://config/ovs/vpools/8455b0ac-6466-40b3-ad82-985cffb2f226/proxies/169d1aba-0807-4d01-8169-362cd4cbbb94/config/abm?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini b851b8fd-2337-4c25-845c-cff0fb927f8e --to-json
{
  "success": true,
  "result": {
    "logical": 33099000952,
    "storage": 49648512096,
    "storage_per_osd": [
      [ 0, 16549504032 ],
      [ 1, 16549504032 ],
      [ 2, 16549504032 ]
    ],
    "bucket_count": [ [ [ 2, 1, 3, 1 ], 8427 ] ]
  }
}
```

**Comment by toolslive** [comment]
it's probably best to change the output of  `show-namespace` to align with the output from `show-namespaces`. Something like this:
```
$>alba show-namespaces .... --to-json
{
  "success": true,
  "result": [
    1,
    [
      {
        "name": "demo",
        "statistics": {
          "logical": 0,
          "storage": 0,
          "storage_per_osd": [],
          "bucket_count": []
        },
        "namespace": {
          "id": 0,
          "name": "demo",
          "nsm_host_id": "nsm",
          "state": "active",
          "preset_name": "default"
        }
      }
    ]
  ]
}

$ alba show-namespace demo --config ... --to-json
{
  "success": true,
  "result": {
    "name": "demo",
    "statistics": {
      "logical": 0,
      "storage": 0,
      "storage_per_osd": [],
      "bucket_count": []
    },
    "namespace": {
      "id": 0,
      "name": "demo",
      "nsm_host_id": "nsm",
      "state": "active",
      "preset_name": "default"
    }
  }
}
```

**Comment by toolslive** [comment]
There are several solutions:
- the above, which will break some OVS test code:
https://github.com/openvstorage/integrationtests/blob/master/ci/tests/backend/alba_test.py#L235-L236

this is done in this branch:
https://github.com/openvstorage/alba/tree/align_show_namespace(s)

the above might also break something for other users....

- adding the fields to the existing call, and do no alignment (which might, 
  but probably will not break anything). 

- add a new call (like `show-namespace2`) with the above proposed behaviour.  Breaks nothing.

- do nothing. You can get at the information by using the `show-namespaces` call and limiting the answer to 1 namespace. Breaks nothing.

@wimpers , @pploegaert :  What do you think?

**Comment by wimpers** [comment]
I would add the field and manage expectations of the existing users by letting them know this change is coming so they are aware.

**Comment by domsj** [comment]
as argued on skype: I think we should go for one of the backwards compatible options.
(side note: in my book adding a field to a json object/dict is perfectly backwards compatible)

being lazy I would redirect users towards the show-namespaces call. that one they can even start using right away (it's available for quite some time already).

**Comment by domsj** [comment]
closing as in my opinion there's nothing to be done here except waste time.
@jeroenmaelbrancke please use show-namespaces (possibly with arguments --first X --finc=true --last X)
