### ISSUE TITLE
Extend get-disk-safety json output

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/alba#403]
As discussed with @domsj.
Is it possible to extend the get-disk-safety on a backward compatible way with following information?

- add (updated) bucket lists including object count
- the amount of objects for the worst safety
- add a flag to simulate the disk safety with all the unavailable disks

**Comment by domsj** [comment]
The unavailable disks mentioned by Jeroen are those that according to the albamgr osd stats
- haven't received reads/writes in the last 15 minutes or
- have errors more recent than latest reads/writes

Not sure what the name of the flag should be...


Another nice option would be `--node-id` (include all osds of this node as dead).
