### ISSUE TITLE
Add call list-jobs

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/alba#407]
Can you add a list-jobs command to Alba that returns all the job names?

**Comment by wimpers** [comment]
@jeroenmaelbrancke which jobs are you talking about? How urgent is this? What is the use case for this call?

**Comment by jeroenmaelbrancke** [comment]
if we manually run a job on alba we are not able to get a list of all the jobs that are running.
Each job that i should launch got a specific name, so if i could list all the jobs and filter the jobs starting with a specific prefix i could remove those jobs when finished.
Each Job (correct me if i'm wrong @domsj ) needs manually removed from the list.

@jtorreke will have a "little" chit chat with you about verify-namespace. (maybe we do not need this feature anymore...)

@domsj what happens if a job fails? Do we need alerting on this or not?

**Comment by wimpers** [comment]
Might be good in that case to update the status of the task with https://github.com/openvstorage/alba/issues/406

**Comment by khenderick** [comment]
@wimpers, these are internal alba tasks, launching them through the framework would not solve anything, since alba processes these asynchronously, so our task finishes immediately.

**Comment by domsj** [comment]
as discussed with @khenderick it would additionally be nice to have a `verify-namespaceS` call, possibly with some `--only-add-if-not-yet-verifying` flag
(and the flags `--namespace` & `--all-namespaces`)

**Comment by wimpers** [comment]
Functionally ready but might cause an arakoon cluster to go down during the upgrade path.

**Comment by toolslive** [comment]
alba 1.3.4
