### ISSUE TITLE
Set fragment size to 16MB by default instead of 1MB for default preset

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/alba#410]
### Problem
The default preset its fragment size must be bumped up to 16MB: https://github.com/openvstorage/framework-alba-plugin/issues/237

During the verification of the ticket, I found that the preset for the default preset is 1MB instead of 16MB.
The default preset and its configuration is delivered by Alba and not by the framework.

### Possible solution
Bump the fragment size to 16 * 1024^2

**Comment by domsj** [comment]
According to @wimpers comment https://github.com/openvstorage/framework-alba-plugin/issues/237#issuecomment-254750793 we shouldn't do anything here?
Personally I would prefer to just remove the default preset. We don't need this concept anyway...
People interpret it as some sort of recommendation, which it most certainly isn't!

(Also, regarding that other ticket: I don't understand why you didn't make the decision to make the fragment size configurable when creating a new preset - that would've been a better choice in my opinion as there is no one-size-fits-all for fragment sizes.)
