### ISSUE TITLE
Counter for invalid checksums per ASD

### ISSUE THREAD

**Issue by wimpers** [openvstorage/alba#423]
OPS proposes to add a counter for for invalid checksums which are encountered when doing a read from an ASD. The idea would be to keep a counter per ASD in the ABM so OPS/monitoring can query the ABM at regular intervals. 

Also add an easy way for OPS to retrieve the counter of course (cli?).

Option to reset the counter per ASD isn't required.

**Comment by wimpers** [comment]
@domsj @toolslive  how much work would this be?

**Comment by toolslive** [comment]
See #463 . The counter was put inside the `osd_info` so you get it whenever you do something like 
```
$> alba list-osds --to-json ...
...
    {
      "id": 0,
      "alba_id": "2e7e6f2d-a85c-484c-ae6c-190252e1497d",
      "kind": "AsdV1",
      ...
      "checksum_errors": 0
    },
...

```
