### ISSUE TITLE
a full osd needlessly leads to repair activity by the maintenance process

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#429]
maintenance detects it can no longer write to the osd and thus considers the osd as 'bad' and tries to repair it

**Comment by wimpers** [comment]
@domsj while working on this one it might be good to implement [Alba osd: provide an implementation for its disk usage](https://github.com/openvstorage/alba/issues/233 )

**Comment by toolslive** [comment]
for the bug: #458
