### ISSUE TITLE
Rora reads from fragment cache: lru tracking using redis

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#433]
When doing partial reads from an alba fragment cache for each read/write the lru tracking in redis should be updated.
When using the ocaml code path this is the case, when using the rora (c++) path (which only does reads) the lru tracking isn't updated.
So in practice when using rora the cache eviction strategy will probably be something closer to fifo than lru.

**Comment by wimpers** [comment]
LRU was removed.
