### ISSUE TITLE
Exit status 0 for commands on error

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/alba#464]
### Problem description
Some alba commands return exit status 0 when they error

I found the issue with these commands:
- alba proxy-create-namespace 
- alba proxy-upload-object
- alba download-object

### Proposed fix
Return exit status 1 or higher (appropriate to the error level) when alba commands error.
### Alba package
alba                                 1.1.0                   amd64                   the ALternative BAckend

**Comment by toolslive** [comment]
#466
