### ISSUE TITLE
No possible method to detect how many bytes/objects need to be fully repaired

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/alba#493]
### Problem description
With the current implementation, we are unable to determine how many objects should be repaired.
This is because the 'applicable_dead_osds', the value to keep in mind when asds are unreachable, is providing us a pessimistic overview of lost objects.
This value is set for every bucket, making it unable to determine how many objects should be repaired.

For instance:
In this case I have purged a single asd. The get-disk-safety is reporting now that there is a remaining safety less than 2. This causes me to think that all of the objects in this bucket should be repaired but in reality only a fraction of these objects were stored on that asd.
```
{
  "success": true,
  "result": [
    {
      "namespace": "c0692edd-d9ec-42fe-af2d-5fcd81d88a4c",
      "safety": 1,
      "safety_count": 378,
      "bucket_safety": [
        {
          "bucket": [ 2, 2, 4, 4 ],
          "count": 378,
          "applicable_dead_osds": 1,
          "remaining_safety": 1
        }
      ]
    },
    {
      "namespace": "fd-myvpool01-dabf14d3-aa6d-4818-aab8-1ea96a5a5efa",
      "safety": null,
      "safety_count": null,
      "bucket_safety": []
    },
    {
      "namespace": "ovs-healthcheck-ns-default",
      "safety": null,
      "safety_count": null,
      "bucket_safety": []
    }
  ]
}

```

**Comment by wimpers** [comment]
Since we can't reliable see how many data needs to repaired, this is considered an SRP.

**Comment by domsj** [comment]
What is expected here?

Alba doesn't know exactly (quickly/cheaply) how much data needs to be repaired.

What alba knows is this:
- how much data resides on a specific osd (which may need repairing)
- how many objects are in each bucket

What alba doesn't know (quickly/cheaply) is:
- how many objects of a certain bucket have fragments on a specific osd
- how many objects have fragments on 2 specific osds

So for what you want here I think we'll have to either
- add more indexes / meta data tracking (and upgrade logic for existing nsms etc)
- add & expose expensive calls
- make an estimate of how many objects in a bucket are affected by an unavailable osd (based on osd usage stats and the assumption that we can just apply this statistic to any bucket) ?

**Comment by wimpers** [comment]
What is expected:

```
{
      "namespace": "c0692edd-d9ec-42fe-af2d-5fcd81d88a4c",
      "safety": 1,
      "safety_count": 378,
      "bucket_safety": [
        {
          "bucket": [ 2, 2, 4, 4 ],
          "missing_count": 15,
          "stored_count": 350,
          "applicable_dead_osds": 1,
          "remaining_safety": 1
        }
      ]
    },
```

Where `stored_count` is the amount of fragments which are stored safely on the disks (exclude fragments on disks dead osds) and where `missing_count` is the amount of fragments which need repair. 

Is it not possible to do this based upon the repair jobs?  This could give us the nr of missing fragments. 
We know what is on each disks so if a disk breaks it should be easy to collect a list of the fragments which are missing?

> how many objects of a certain bucket have fragments on a specific osd
How do you repair an OSD in that case? Don't you need that to quickly repair an OSD?

If it would make you life easier to do this on complete SCO basis instead of fragment, that would be fine too. In that case `stored_count` would be the objects where all fragments are stored.

**Comment by toolslive** [comment]
> how many objects of a certain bucket have fragments on a specific osd
> How do you repair an OSD in that case? Don't you need that to quickly repair an OSD?

Alba knows _which_ objects have fragments on a certain OSD. If that OSD dies, this index is used to repair these objects. At that point, it just has a (huge) list of object identifiers. It doesn't know how large that list is, and it doesn't know how much data is involved (as the fragments may have different sizes)

**Comment by toolslive** [comment]
_on SCO basis_?

**Comment by wimpers** [comment]
`stored_count`: the amount of SCOs stored in the namespace
 `missing_count`: The amount of SCOs which have 1 or more fragments missing:

on SCO basis means that you provide per namespace how much SCOs are stored ok and how many not ok so OPS has an idea of in which a good/bad shape the namespace is.

**Comment by toolslive** [comment]
Alba does not know what a SCO is, and a namespace does not only contain SCOs. Our main client, volume driver stores other stuff as well, like fe snapshot.xml files.

**Comment by wimpers** [comment]
Back to BAM for discussion

**Comment by wimpers** [comment]
@saelbrec  and @wimpers to decide how to tackle.

**Comment by wimpers** [comment]
Since there is no request for this info from OPS closing it down. Re-open if needed.
