### ISSUE TITLE
Remove  k <= c restriction

### ISSUE THREAD

**Issue by wimpers** [openvstorage/alba#516]
Remove the restriction k <= c  for policies in an ALBA backend.

**Comment by saelbrec** [comment]
In case maintenance would have to repair a missing data fragment after a proxy failed, a policy where c < k would lead to dataloss. This might be acceptable for an alba backend being used as fragment cache but for sure not advisable for any others.

What do we actually want to achieve with this 'enhancement' ?

**Comment by wimpers** [comment]
After discussion with stakeholders: don't remove the restriction.
