### ISSUE TITLE
Failure "can't happen" exception

### ISSUE THREAD

**Issue by dejonghb** [openvstorage/alba#537]
Found 12 messages as this little gem in the logs:
```
Dec 29 16:50:24 ftcmp02 alba[11847]: 2016-12-29 16:50:24 142163 +0100 - ftcmp02 - 11847/0 - alba/proxy - 11068 - info - Exception while adding object to alba fragment cache: (Failure "can't happen"); backtrace:; Raised at file "format.ml", line 241, characters 41-52; Called from file "format.ml", line 482, characters 6-24
```
The proxy was running in debug mode and 7 of these are on debug level, 5 on info.

**Comment by domsj** [comment]
On the same env we also saw https://github.com/openvstorage/alba/issues/209 .
This issue is probably caused by the other issue.
(The logic in choose.ml doesn't like negative fill rates...)
