### ISSUE TITLE
Partial-strings of alba commands are executed as the full command

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/alba#538]
### Problem description
The CLI parser of Alba corrects typos and such but it does not expect the full commando.

This can be seen here:
```
alba: required option --config is missing
Usage: alba list-presets [OPTION]... 
Try `alba list-presets --help' or `alba --help' for more information.
```
I typed in list-preset and list-presets got interpreted.

**Comment by toolslive** [comment]
It's `cmdliner` that's doing this. I'm curious though: how/where is this causing problems?
