### ISSUE TITLE
Support for redis clusters in Ocaml client

### ISSUE THREAD

**Issue by wimpers** [openvstorage/alba#551]
Based upon a discussion in https://github.com/openvstorage/framework/issues/1119 this ticket is created. 
The ocaml redis client currently has no support for that, so this ticket is created for having that supported.

**Comment by domsj** [comment]
The ocaml-redis library that we use now has support for redis cluster: https://github.com/0xffea/ocaml-redis/pull/51 . So if desired we could integrate this.

**Comment by wimpers** [comment]
Not required for now as we switched from LRU to random eviction.

**Comment by wimpers** [comment]
Closing this one down as we no longer use Redis for LRU.
