### ISSUE TITLE
Don't disqualify ASDs (immediately) on a broken pipe

### ISSUE THREAD

**Issue by khenderick** [openvstorage/alba#596]
After some discussions with @domsj:

Don't disqualify ASDs (immediately) on a broken pipe. If for example an update or a storagenode reboot causes all ASD processes to be restarted, the proxies will have all their connection pipes being broken. The proxy would then disqualify all ASDs and need to wait for the requalification process to qualify all the ASDs again. This happens when the ASDs are already running fine.

A better approach might be to handle a broken pipe different. The proxy could for example suspect an ASD reboot and immediately re-try connecting. If that succeeds, everything is fine and things move on smoothly. If the connection cannot be established, the ASD can be disqualified.

**Comment by toolslive** [comment]
#746 (dyslexia strikes)
