### ISSUE TITLE
Subset between max asd usage and min asd usage increase when removing asds

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/alba#627]
On OVH we have an accel backend with preset 4,1,4,1 (11 nodes with 4 asds/node)
When we removed 2 asds on a node the usage of the 2 other asds increased rapidly.
This triggered the alarm that the subset between the max and min usage is >2%.

error:
```
CRIT - Subset between the osds: 9.28% (warn/crit at 1.0%/2.0%)
```

data spread in %:
![data_spread](https://cloud.githubusercontent.com/assets/2900612/23453603/42ba8564-fe69-11e6-9740-1559a18e169a.png)

asd usage:
![asd_usage](https://cloud.githubusercontent.com/assets/2900612/23453609/4c80e002-fe69-11e6-9b48-45ee6a70b33a.png)

![asd_usage_when_deleting_asds](https://cloud.githubusercontent.com/assets/2900612/23456223/d57627ba-fe72-11e6-81be-885f2b595100.png)

The asd usage is now dropping again after 10h.

**Comment by jeroenmaelbrancke** [comment]
and now the asds is dropping (the mount usage is the sum of 2 asds):

![asd_info](https://cloud.githubusercontent.com/assets/2900612/23455724/e7c45416-fe70-11e6-8227-2aa41fb26ba9.png)

min usage:
![node_min_usage](https://cloud.githubusercontent.com/assets/2900612/23455775/1e43f668-fe71-11e6-892e-6a596eb95856.png)

max usage:
![node_max_usage](https://cloud.githubusercontent.com/assets/2900612/23455778/2173688c-fe71-11e6-99c2-24fdccaa374f.png)

**Comment by jeroenmaelbrancke** [comment]
and the asds are now at 99%.

![asd_usage](https://cloud.githubusercontent.com/assets/2900612/23516356/489b6db8-ff6d-11e6-8856-3535a89f9f6d.png)

spread:
![data_spread](https://cloud.githubusercontent.com/assets/2900612/23516367/4da94cda-ff6d-11e6-8914-1fa1ecb4fea2.png)

**Comment by wimpers** [comment]
Is this expected, pelase shine your light on the issue @domsj @toolslive

**Comment by domsj** [comment]
So far for me it's unexpected. Probably the asymmetricity of the setup is somehow involved.
Regarding warning 1, critical 2: I don't think it makes sense to wake somebody up if this issue should occur.
As long as the backend is writeable at max you want to see a warning about this in the monitoring gui.

**Comment by wimpers** [comment]
@jeroenmaelbrancke  see Jan's comment to change the critical to warning so you aren't alarmed at night.

**Comment by jeroenmaelbrancke** [comment]
Alerting has been disabled but will not been cleaned in Check_mk.
Thresholds are still the same 1% warning and 2% critical or should we increase this?

![image](https://user-images.githubusercontent.com/2900612/27120563-5a25f300-50e4-11e7-98b5-af8585f0e707.png)

**Comment by wimpers** [comment]
@saelbrec please advise

Depending on the amount of times (happening every day is bad) this occurs I would increase it to maybe 5-10%.

**Comment by wimpers** [comment]
@toolslive any suggestions for this one. Should OPS use bigger thresholds?

**Comment by toolslive** [comment]
`subset between the max and min usage is >2%.`
I don't know what it means.
I have been looking at some backends with bad distribution
And saw the following statistics from one of the maintenance agents:
```
statistics:{
   creation: 2018/05/17_13:42:41.5439;;
   period: 47092.17;
   Clean_obsolete : {
       n = 1261573L;
       avg = 0.170138617503; ...
       min = 0.00826096534729;;  max = 107.386172056; alpha = 0.9 };
       Histo { 0.01:27; 0.1:990483; 0.5:200993; 1:35266; 2:19204; 5:10920; 10:3147; 
                  1e+04:1533; };
   Rebalance : {
       n = 3608L; 
   };
   Repair_generic_time : {
       n = 2403L;
       avg = 2.49901522362; ...
       min = 0.0157608985901;
       max = 127.25029707;};
       Histo { 0.1:998; 0.5:953; 1:189; 2:57; 5:55; 10:30; 
                  1e+04:121; };

   Rewrite_object : {
       n = 61L;
       avg = 4.11826050086; ...
       min = 0.0780780315399;
       max = 30.4550690651;;  alpha = 0.9 };;
       Histo { 0.1:3; 0.5:11; 1:9; 2:12; 5:9; 10:9; 1e+04:8; };
}
```
The dominant activity is cleanup, beating rebalance 350/1.
So why do we create so much waste?
That backend has the following distribution:

interval     | count
-------------|--------- 
[60-65%) | 7
[65-70%) | 28
[80-85%) | 25
[85-90%) |  1

**Comment by wimpers** [comment]
@toolslive can this one be closed as this is expected? I believe this is the same scenario as the full ASD scenario where the setup is async?

**Comment by toolslive** [comment]
This will happen if for example in a setup where all nodes have 4 ASDs except for 1 node that has only 1 ASD. The natural tendency is to have this solitary ASD filled up before the others even reach 50%. Rebalancing will delay this somewhat.
