### ISSUE TITLE
lots of Alba_client_preset_cache.propagate_preset logging

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#639]
This log line isn't very informative and was seen quite a lot (more than expected?) on the OVH env. To be investigated.

**Comment by domsj** [comment]
@jeroenmaelbrancke do you still see this now? what if you restart maintenance?
Wondering if it maybe had something to do with the maintenance work backlog that triggered this...

**Comment by jeroenmaelbrancke** [comment]
Yep, still seeing this on the maintenance agent.
![propagate_preset](https://cloud.githubusercontent.com/assets/2900612/23708211/7a36d14e-0415-11e7-929b-993cca9bed78.png)

**Comment by wimpers** [comment]
@domsj if you can fix between soup and potatos for RC4, change the milestone.

**Comment by wimpers** [comment]
@domsj I believe you would fix this between soup and potatos. Did that happen in the end?

**Comment by domsj** [comment]
not yet. looked at it a bit already, but wasn't able to finish it so far

**Comment by wimpers** [comment]
@jeroenmaelbrancke do we still see this one?

**Comment by jeroenmaelbrancke** [comment]
The amount has been dropped to 65 for one day for all the maintenance agent.
```
root@NY1SRV0024:/mnt/monitoring/rsyslog/client_logs/NY1SRV1000# grep 'preset_cache' alba.log | wc
     65    1430   12806
```

You can close the ticket.

**Comment by wimpers** [comment]
See last remark , closing this ticket. Re-open if needed.
