### ISSUE TITLE
broken objects in cache namespaces should be cleaned up

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#641]
It makes no sense to keep around metadata for objects for which no fragments are still available. Maintenance should clean these up.
Not sure if it makes sense to keep around objects for which some fragments (less than k) are still available?
(It could still serve some read requests, so they have at least some value...)

**Comment by wimpers** [comment]
> Not sure if it makes sense to keep around objects for which some fragments (less than k) are still available?

To be discussed. maybe leave as is in a first version. Do we track how many fragments are still in cache?
