### ISSUE TITLE
Finer grained ssd caching

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#655]
Currently caching of hdd data onto ssds is done on a fragment level granularity, using the alba proxy fragment cache feature. The fragment cache can be either a local ssd or another (ssd-based) alba.

For some use cases however it may make more sense to do finer grained caching, for example based on slices of 128KB or 256KB of data.

**Comment by wimpers** [comment]
To be picked up in https://github.com/openvstorage/alba_ee/issues/14
