### ISSUE TITLE
centos 7 build result is broken

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#720]
The binary / package still builds, but the binary exits before doing any usefull work on an assert about the libgcrypt version - which isn't met.
This was introduced in https://github.com/openvstorage/alba/pull/697 aka as of 1.3.13.

This fails on travis too, see e.g. https://travis-ci.org/openvstorage/alba/jobs/234731563, but the error gets swallowed somewhere in the process.

**Comment by toolslive** [comment]
centos-7 docker instructions will still install `1.5.3-13.el7_3.1` while the assert moved to 1.6.0

**Comment by domsj** [comment]
fixed by #723
