### ISSUE TITLE
Update preset fails with Failure Preset.Update.t.fragment_size

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/alba#734]
As observed on:

unstable: arakoon 1.9.18 - alba-ee 1.5.1
develop: arakoon 1.9.17 - alba-ee 1.5.0

Updating an existing preset fails with:

```Failure Preset.Update.t.fragment_size```

According to @domsj probably regression since alba 1.5.0

**Comment by toolslive** [comment]
is EE feature.
