### ISSUE TITLE
Local backend is disqualified because on namespace already exists

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/alba#737]
On the global proxies we see following error:
```
Disqualifying osd 1: Albamgr_protocol.Protocol.Error.Albamgr_exn(4, "Albamgr_protocol.Protocol.Error.Namespace_already_exists"); backtrace:; Raised at file "map.ml", line 122, characters 16-25; Called from file "src0/sexp_conv.ml", line 149, characters 10-37
```

similar issue: #550 

Why do we get these errors? Can you improve this error?

**Comment by wimpers** [comment]
@jeroenmaelbrancke  any idea why the namespace was created multiple times?

**Comment by domsj** [comment]
My current best guess: possibly multiple different namespaces were created on the main backend around the same time.
This could cause a race in the osd message delivery where 2 proxies try to create the same local backend namespace simultaneously.
Alba will/should correctly recover from the race, but a local-backend-osd might be temporarily disqualified.
If the hypothesis is correct this can be solved by suppressing the Namespace_already_exists error here: https://github.com/openvstorage/alba/blob/1.3.16/ocaml/src/alba_osd.ml#L193-L197.
