### ISSUE TITLE
Provide identical stats for Active Drives

### ISSUE THREAD

**Issue by khenderick** [openvstorage/alba#745]
At this moment, we ask the ABM for various statistics related to the ASD. As more types of drives (like the Active Drive) are added, we'd like to ask these in the same flow.

Reference: https://github.com/openvstorage/framework-alba-plugin/issues/415#issuecomment-306792091

**Comment by domsj** [comment]
Are you referring to the output from `alba list-osds` or `alba asd-multistatistics` ?
The first should be in the same format, the second is asd specific (see the name)

**Comment by wimpers** [comment]
@domsj  how much work is this?

**Comment by toolslive** [comment]
what's an active drive?

**Comment by toolslive** [comment]
``` 
{ "success": true,
  "result": {
    "active_drive_id": {
      "success": true,
      "result": {
        "capacity": 11997998481408.0,
        "version": [ 8, 0, 2, "...." ]},
        ...
    }
}
```
something like this is the best we can do. (that's worthless, as you get there from `list-osds`)
