### ISSUE TITLE
Provide osd-multistatistics

### ISSUE THREAD

**Issue by khenderick** [openvstorage/alba#749]
Like `asd-multistatistics`, we'd like to have a more generic `osd-multistatistics` that does the same, but can also collect information from other types of OSDs (ASD, Active Drive, but not another backend).

**Comment by wimpers** [comment]
@toolslive @domsj  isn't this a duplicate of https://github.com/openvstorage/alba/issues/745

**Comment by wimpers** [comment]
After discussion with @toolslive closed as duplicate
