### ISSUE TITLE
global backend leaks objects when creating and deleting a namespace

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#774]
more precisely in the 'global_kvs' namespace (with name = 'prefix') that is created on each local backend the following keys are leaked:
```
  "p\000\000\000\000n\000\000\000\024";
  "p\000\000\000\000n\000\000\000\024n";
```

**Comment by domsj** [comment]
the leaking has stopped since #776, but a cleanup script for affected backends remains to be written

**Comment by wimpers** [comment]
@ops can you guys a script for the cleanup of affected  namespaces?

**Comment by domsj** [comment]
fwiw I actually already started working on a cli addition for this
