### ISSUE TITLE
proxy-download-object does not redirect the file to where the command was executed

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/alba#830]
### Problem description
I'd assume that a proxy would redirect everything I ask it to back to my localhost. This is not the case witht the proxy-download-object.
`alba proxy-download-object --host=OTHER_IP --port=A_PORT A_NAMESPACE AN_OBJECT MY_LOCAL_PATH` will download the object to the filesystem of OTHER_IP instead the local one

**Comment by domsj** [comment]
fixed in https://github.com/openvstorage/alba_ee/pull/269
